name = "ClearswiApp"
uuid = "05b4817b-e4a0-4589-8b6a-5b9ef9b94bee"
authors = ["Korbinian Eckstein korbinian90@gmail.com"]
version = "1.2.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ArgParse = "1"
MriResearchTools = "1.0"
Pkg = "1"
julia = "1.5"
