name = "ClearswiApp"
uuid = "05b4817b-e4a0-4589-8b6a-5b9ef9b94bee"
authors = ["Korbinian Eckstein korbinian90@gmail.com"]
version = "1.2.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CLEARSWI = "06ae4d9b-ce5e-4813-a1b3-426e46312ec2"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"

[compat]
ArgParse = "1"
CLEARSWI = "1.0"
MriResearchTools = "1.0"
julia = "1.5"
